### ISSUE TITLE
unicode gotcha

### ISSUE THREAD

**Issue by cleder** [ulope/pyformat.info#20]
from http://stackoverflow.com/questions/5082452/python-string-formatting-vs-format

But please be careful, just now I've discovered one issue when trying to replace all % with .format in existing code: '{}'.format(unicode_string) will try to encode unicode_string and will probably fail.

**Comment by ulope** [comment]
This seems to be another consequence of Python 2's inconsistent str/unicode handling.

Since the site is focused on string formatting I'm not sure whether we should get into the whole encoding business. Maybe we should add a small note with a link to someplace that explains the problem.

**Comment by zerok** [comment]
While the included examples are for Python 2.x and 3.x I'm :-1:  on including any reference to encoding issues here esp. given the vast differences between the Unicode handling of 2.x and 3.x.

**Comment by ulope** [comment]
@zerok I agree.
@cleder thanks for the report, but we want this site to stay focused on the formatting aspects
