### ISSUE TITLE
Example layout differs between Safari and Chrome/FF

### ISSUE THREAD

**Issue by ulope** [ulope/pyformat.info#22]
Chrome/FF:
![Chrome](http://cl.ly/image/32190l2G0d3i/Image%202015-08-18%20at%203.35.54%20nachm..png)

Safari:
![Safari](http://cl.ly/image/0q1M422D040d/Image%202015-08-18%20at%203.36.21%20nachm..png)

@zerok Do you remember which was the one you originally intended?

**Comment by zerok** [comment]
The Safari one. Will look into it tomorrow.
