### ISSUE TITLE
www.pyformat.info serves invalid SSL certificate

### ISSUE THREAD

**Issue by The-Compiler** [ulope/pyformat.info#27]
While https://pyformat.info/ works fine, https://www.pyformat.info/ presents an invalid SSL cert:

```
$ http https://www.pyformat.info

http: error: SSLError: hostname 'www.pyformat.info' doesn't match either of 'dali.ulo.pe', 'docker.ulo.pe', 'ipy.ulo.pe', 'piwik.ulo.pe', 'znc.ulo.pe', 'git.ulo.pe', 'ip.ulo.pe', 'ulo.pe'
```

I'd expect that to work as well.

(Also, thanks a lot for pyformat.info!)

**Comment by ulope** [comment]
Indeed it should. And now it does :)

Thanks for the report.
