### ISSUE TITLE
How to substitute variables into string by name?

### ISSUE THREAD

**Issue by hickford** [ulope/pyformat.info#28]
In Ruby you can substitute variables into strings by name:

	> origin = "London"
	> destinatio­n = "Paris"
	> "from #{ori­gin} to #{destination}"­
	=> "from London to Paris"

C# 6 has a similar feature:

	string name = "Alice";
	Console.WriteLine($"Hello {name}");

How do you do it in Python?

**Comment by hickford** [comment]
If it's not possible, I think it would be still worth a note in your guide https://pyformat.info/

**Comment by zerok** [comment]
Python 3.6 will include an implementation PEP0498 which is all about that :)
For pyformat.info itself, we have with #24 already a ticket about how this might eventually be integrated into the site :) I'm closing this ticket here in favor of #24 .

**Comment by hickford** [comment]
Great that's exciting, I didn't know about that

https://www.python.org/dev/peps/pep-0498/

**Comment by zerok** [comment]
Personally, I don't really see the need for it but we will think about how to integrate it into pyformat.info :)
