### ISSUE TITLE
multiline string example

### ISSUE THREAD

**Issue by thorade** [ulope/pyformat.info#41]
Could you add an example that uses strings longer than [72 ](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)characters?

Here is one example using triple quotes, nothing unexpected I guess:

```python
value = 1e-4
tolerance = 1e-6
print("""ERROR: Found x with value={!s} 
which is much bigger and add a long text for demo here
than the maximum tolerance of {!s}.""".format(value, tolerance))
```

And here is the same example using line contiuation, so that the output is on a single line:
```python
value = 1e-4
tolerance = 1e-6
print("ERROR: Found x with value={!s} \
which is much bigger and add a long text for demo here \
than the maximum tolerance of {!s}.".format(value, tolerance))
```

**Comment by thorade** [comment]
Update: I am unsure about the correct indentation, this is how I expected it to be correct:
```python
condi1 = True
condi2 = True
value = 1e-4
tolerance = 1e-6

if condi1:
    print("ERROR: Found x with value={!s} \
           which is much bigger and add a long text for demo here \
           than the maximum tolerance of {!s}.".format(value, tolerance))

print()

if condi2:
    print("""ERROR: Found x with value={!s} 
             which is much bigger and add a long text for demo here
             than the maximum tolerance of {!s}.""".format(value, tolerance))
```
but that has too much spaces.
Do new lines in the long string have to be un-indented?

**Comment by ulope** [comment]
Hi, thanks for the issue. 
However I'm not quite sure what the point of this example would be. 
Multiline strings and line continuation are general Python syntax features and IMO not really in scope for a site that focuses on string formatting.
