### ISSUE TITLE
Footer Version Link is Broken

### ISSUE THREAD

**Issue by retnikt** [ulope/pyformat.info#45]
The link in the footer:

> Version: 516238e0e82853567ca7ba20adcbd634b8b8458a (built at 2016-12-27 19:30:23.236195+00:00)

which links to [https://github.com/ulope/pyformat.info/tree/516238e0e82853567ca7ba20adcbd634b8b8458a](https://github.com/ulope/pyformat.info/tree/516238e0e82853567ca7ba20adcbd634b8b8458a) gives a 404 Error.

![capture](https://cloud.githubusercontent.com/assets/24581770/25562098/e4a52396-2d73-11e7-8953-b08cdb3be3cb.PNG)

**Comment by ulope** [comment]
Strange... No idea how this happened. I've redeployed the site - the link is fixed now.

Thanks for reporting this!
