### ISSUE TITLE
Zero in scientific notation

### ISSUE THREAD

**Issue by pcagas** [ulope/pyformat.info#53]
Formating zero `print("{:e}".format(0.0))` returns `0.000000e+00` Based on the mathematitian you ask, 0^0 is either 1 or indetermined. It would be much better if the result was  `0.000000e+01`

**Comment by pcagas** [comment]
Sorry

**Comment by ulope** [comment]
If you feel strongly about this I’d recommend to open an issue in the python bug tracker: https://bugs.python.org
